"""aido — the public AIDO CLI (P1).

Removes the need for a user to write a custom Python harness
(``scripts/run_external_project_pilot.py`` remains real implementation
evidence, not the product surface). Consumes ``ProjectConfig`` (P12) and
``ProjectRuntime`` — this module stays thin: argument parsing and plain-
text presentation only. It never composes stores/services itself and
never contains WorkItem-scheduling logic (``MVPManager`` stays
authoritative).

Four commands, deliberately no more (KISS/YAGNI):

- ``aido init``     — scaffold a project, or write an ``aido.yaml`` template.
- ``aido validate`` — load/validate a config, print facts, no side effects.
- ``aido run``      — bootstrap (idempotent) + drive WorkItem Flow to
  completion/WAITING/max-cycles. Also the resume operation — there is no
  separate ``aido resume``: re-running ``aido run`` against the same
  config reopens the same persisted state (``ProjectConfig.project.state_dir``)
  and continues via the existing WAITING/RECOVERY_REQUIRED mechanisms.
- ``aido status``   — read persisted state, no provider calls, no
  mutation.

Exit codes (deliberately simple):

- ``0``: the CLI operation itself completed successfully — including a
  project that is legitimately ``WAITING`` or has nothing currently due.
  ``WAITING`` is a valid durable orchestration state, never a CLI failure.
- ``1``: an operational/configuration failure — invalid config, a
  persisted-state/config conflict, provider/backend composition
  impossible, or an actual orchestration error.
- ``2``: usage error (argparse's own standard behavior).

Only ``aido run`` ever causes a real provider probe or worker execution.
``init``/``validate``/``status`` are provider-call-free by construction —
none of them ever call ``ProjectRuntime.open()`` and ``bootstrap()``
followed by ``MVPManager.run_next_work_item(...)``.

LEGACY/TRANSITIONAL SURFACE: this CLI is ``ai-dev-orchestrator``'s own
historical product surface, kept working for existing users/tests, but it
is not this project's product going forward — ``ai-dev-orchestrator`` is
now positioned as an engine/library an embedding application (AIDO Code)
drives through ``orchestrator.engine.OrchestratorEngine`` instead (see
ROADMAP.md, "engine/library boundary"). This module is never extended
with new product-facing responsibility; it still relies on the legacy,
file-based ``workers.registry`` reading every ``aido.yaml`` it loads
(``ProjectConfig.load_worker_registry()``) — the modern engine API does
not require this and instead expects an injected ``WorkerRegistry``
(``OrchestratorEngine(..., worker_registry=...)``).
"""

from __future__ import annotations

import argparse
import asyncio
import re
import shlex
import shutil
import subprocess
import sys
from pathlib import Path

from orchestrator.engine import EngineConfigError, OrchestratorEngine
from orchestrator.execution_policy import ExecutionPermissionMode
from orchestrator.project_config import MissingGitWorkspaceError, ProjectConfig, ProjectConfigError
from orchestrator.project_runtime import (
    ConfigRuntimeConflictError,
    ProjectRuntime,
    ProjectRuntimeError,
)
from orchestrator.project_state import WorkItemStatus
from orchestrator.worker_registry import UnknownWorkerError, WorkerRegistry, WorkerRegistryError

DEFAULT_CONFIG_PATH = "./aido.yaml"
DEFAULT_MAX_CYCLES = 50

_TERMINAL_STATUSES = frozenset(
    {WorkItemStatus.COMPLETED, WorkItemStatus.FAILED, WorkItemStatus.BLOCKED}
)
# Reported status counts — REVIEWING is legacy decode-only (see
# WorkItemStatus's own docstring), never a current WorkItem Flow phase,
# so it is deliberately excluded from this user-facing summary.
_REPORTED_STATUSES = tuple(s for s in WorkItemStatus if s is not WorkItemStatus.REVIEWING)


def _yaml_str(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _sanitize_id(name: str) -> str:
    slug = re.sub(r"[^a-z0-9-]+", "-", name.lower()).strip("-")
    return slug or "project"


def _load_config(path: str) -> ProjectConfig | None:
    """Loads a config, printing one clean line (never a traceback) for an
    ordinary bad config/worker-registry problem."""
    try:
        return ProjectConfig.load(path)
    except MissingGitWorkspaceError as exc:
        print("aido: this project is not initialized as a Git repository.", file=sys.stderr)
        _print_git_recovery(exc.workspace)
        print(f"Then retry:\n  aido validate {shlex.quote(str(Path(path).resolve()))}")
        return None
    except (ProjectConfigError, WorkerRegistryError) as exc:
        print(f"aido: invalid project configuration — {exc}", file=sys.stderr)
        return None


# --- aido init ---------------------------------------------------------

_INIT_TEMPLATE = """\
# Generated by `aido init` — EDIT ME before running `aido validate`/`aido run`.
# See docs/PROJECT_CONFIG.md for the full schema reference.

schema_version: 1

project:
  id: {project_id}
  name: {project_name}
  workspace: {workspace}
  # state_dir omitted on purpose — defaults deterministically to
  # ~/.local/state/ai-dev-orchestrator/projects/{project_id_raw}/

workers:
  registry: {registry}

execution:
  permission_mode: {permission_mode}

git:
  base_branch: main

mvp:
  id: mvp-1
  objective: "TODO: describe the first governed slice of real product work."
  acceptance_criteria:
    - "TODO: state, concretely, what 'done' means for this MVP."

work_items:
  # EXAMPLE WorkItem template — AIDO cannot infer your acceptance
  # criteria automatically. Replace this with your own WorkItem(s).
  - id: wi-1
    title: "TODO: describe the first WorkItem"
    required_capabilities: [development]
    dependencies: []
    acceptance_criteria:
      - "TODO: state, concretely, what 'done' means for this WorkItem."

qa:
  # TODO: define the real QA commands for this project.
  # A common default, only if your project actually uses pytest —
  # replace or remove this if it does not. AIDO never guesses your real
  # QA commands beyond this one safe, widely-applicable template.
  - id: qa-tests
    kind: unit_test
    argv: ["pytest", "-q"]
    timeout_seconds: 300
    required: true
"""


def _default_worker_registry_text() -> str:
    """The canonical worker registry template packaged inside this
    distribution's own wheel (P13.3, see ROADMAP.md) — never the
    ai-dev-orchestrator source checkout's ``config/workers.yaml`` (a
    ``pip install``-only user has no such checkout at all). No secret/
    API key/credential/machine path — see
    ``tests/test_default_worker_registry.py``."""
    from importlib.resources import files as _resource_files

    return _resource_files("orchestrator.resources").joinpath("default_workers.yaml").read_text()


def _user_worker_registry_path() -> Path:
    """``$XDG_CONFIG_HOME/ai-dev-orchestrator/workers.yaml``, or
    ``~/.config/ai-dev-orchestrator/workers.yaml`` if unset — a real
    user's own editable copy, independent of any source checkout."""
    import os

    base = os.environ.get("XDG_CONFIG_HOME")
    config_home = Path(base).expanduser() if base else Path.home() / ".config"
    return config_home / "ai-dev-orchestrator" / "workers.yaml"


def _materialize_user_worker_registry() -> Path:
    """Creates the user's own worker registry from the packaged default
    template if (and only if) it does not already exist — an existing
    user file, however it got there, is never overwritten. Returns its
    path either way."""
    path = _user_worker_registry_path()
    if not path.is_file():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(_default_worker_registry_text())
        print(f"aido init: no --workers-registry given; created a starter registry at {path}")
    else:
        print(f"aido init: no --workers-registry given; using existing {path}")
    return path


def _write_init_config(args: argparse.Namespace) -> int:
    config_path = Path(args.config).expanduser().resolve()
    if config_path.exists():
        print(f"aido init: {config_path} already exists — refusing to overwrite.", file=sys.stderr)
        return 1

    if args.workers_registry:
        registry_path = Path(args.workers_registry).expanduser().resolve()
    else:
        # Today's development convenience (a sibling `config/workers.yaml`
        # in the current directory, e.g. this very repository) still
        # wins if present, so nothing about the existing dev loop
        # changes. Standalone (pip install only, no such checkout): fall
        # back to a real, materializable user registry — never require a
        # source checkout (P13.3).
        candidate = Path.cwd() / "config" / "workers.yaml"
        if candidate.is_file():
            registry_path = candidate.resolve()
            print(f"aido init: no --workers-registry given; using existing {registry_path}")
        else:
            registry_path = _materialize_user_worker_registry()

    if not registry_path.is_file():
        print(f"aido init: worker registry not found: {registry_path}", file=sys.stderr)
        return 1
    try:
        from orchestrator.worker_registry import WorkerRegistry

        WorkerRegistry.load(registry_path)
    except WorkerRegistryError as exc:
        print(f"aido init: invalid worker registry {registry_path}: {exc}", file=sys.stderr)
        return 1

    config_dir = config_path.parent
    workspace_path = Path(args.workspace).expanduser().resolve() if args.workspace else config_dir
    try:
        workspace_rel = Path(_relpath(workspace_path, config_dir))
    except ValueError:
        workspace_rel = workspace_path
    try:
        registry_rel = Path(_relpath(registry_path, config_dir))
    except ValueError:
        registry_rel = registry_path

    project_id = args.project_id or _sanitize_id(workspace_path.name)
    project_name = args.project_name or workspace_path.name
    permission_mode = args.permission_mode or ExecutionPermissionMode.STANDARD.value

    content = _INIT_TEMPLATE.format(
        project_id=_yaml_str(project_id),
        project_id_raw=project_id,
        project_name=_yaml_str(project_name),
        workspace=_yaml_str(str(workspace_rel)),
        registry=_yaml_str(str(registry_rel)),
        permission_mode=permission_mode,
    )
    config_path.write_text(content)
    print(f"aido init: wrote {config_path}")
    print("Edit it — especially mvp.objective/acceptance_criteria and work_items "
          "— then run `aido validate`.")
    return 0


_README_TEMPLATE = """# {name}

## Purpose

TODO: What problem does this project solve?

## Users

TODO: Who is this project for?

## Main constraints

TODO: Technical, functional or operational constraints.

## Development

This project is developed through AI Dev Orchestrator.

See:
- ROADMAP.md
- aido.yaml
"""

_ROADMAP_TEMPLATE = """# ROADMAP — {name}

## Vision

TODO: Describe the target outcome.

## M1 — First usable increment

### Objective

TODO

### Acceptance criteria

- TODO

### Scope

TODO

### Out of scope

TODO
"""

# Runtime noise convention shared with GitGovernanceService; state databases
# normally live outside the project in the user's state directory.
_INIT_GITIGNORE = "/.ralph/\n.env\n.env.*\n"


def _print_git_recovery(workspace: Path) -> None:
    print(f'\nFrom {workspace} run:\n\n  cd {shlex.quote(str(workspace))}\n'
          '  git init -b main\n  git add .\n'
          '  git commit -m "Initialize AIDO project"\n')


def _initialize_project_git(workspace: Path) -> bool:
    git = shutil.which("git")
    if git is None:
        print("WARNING: Git is not installed or is not available in PATH.")
        print("\nAIDO requires a Git repository before governed development can start.")
        print("After installing Git:")
        _print_git_recovery(workspace)
        return False
    for command in (["init", "-b", "main"], ["add", "."],
                    ["commit", "-m", "Initialize AIDO project"]):
        try:
            subprocess.run([git, *command], cwd=workspace, check=True,
                           capture_output=True, text=True, timeout=60)
        except (OSError, subprocess.SubprocessError) as exc:
            print(f"aido init: Git step '{command[0]}' failed. Scaffold preserved.", file=sys.stderr)
            detail = str(getattr(exc, "stderr", "") or exc)
            print(detail, file=sys.stderr)
            if any(marker in detail.lower() for marker in
                   ("identity", "user.email", "user.name", "auto-detect email", "who you are")):
                print("Configure your Git identity before retrying the commit.", file=sys.stderr)
            _print_git_recovery(workspace)
            return False
    return True


def _cmd_init(args: argparse.Namespace) -> int:
    try:
        if args.new_project is None:
            return _write_init_config(args)
        return _scaffold_project(args)
    except (OSError, ValueError) as exc:
        print(f"aido init: {exc}", file=sys.stderr)
        return 1


def _scaffold_project(args: argparse.Namespace) -> int:
    name = args.new_project
    # One portable directory component, never a path, option or control text.
    if not re.fullmatch(r"[^\W_][\w .-]*", name) or name.endswith((".", " ")):
        print("aido init: project-name must be a single directory name, not a path. "
              "No file was modified.", file=sys.stderr)
        return 1
    if args.workspace is not None or args.project_name is not None:
        print("aido init: --workspace and --project-name belong to the legacy config mode; "
              "the two positional arguments define the new project. No file was modified.",
              file=sys.stderr)
        return 1
    parent = Path(args.config).expanduser().resolve()
    target = parent / name
    if target.is_symlink():
        print(f"aido init: {target} is a symlink. No file was modified.", file=sys.stderr)
        return 1
    if target.exists() and (not target.is_dir() or any(target.iterdir())):
        print(f"aido init: {target} already exists and is not empty.\nNo file was modified.",
              file=sys.stderr)
        return 1
    target.mkdir(parents=True, exist_ok=True)
    config_args = argparse.Namespace(**vars(args))
    config_args.config = str(target / "aido.yaml")
    config_args.workspace = str(target)
    config_args.project_name = name
    if _write_init_config(config_args) != 0:
        return 1
    for filename, content in (("README.md", _README_TEMPLATE.format(name=name)),
                              ("ROADMAP.md", _ROADMAP_TEMPLATE.format(name=name)),
                              (".gitignore", _INIT_GITIGNORE)):
        (target / filename).write_text(content, encoding="utf-8")
    git_ready = _initialize_project_git(target)
    print("\nAIDO — project initialized" if git_ready else "\nAIDO — scaffold created; Git setup incomplete")
    print(f"\nProject: {name}\nDirectory: {target}")
    if git_ready:
        print("Git: initialized on branch main\nInitial commit: created")
    print("\nFiles created:\n  README.md\n  ROADMAP.md\n  aido.yaml\n  .gitignore")
    print(f"""
Next steps:

1. cd {shlex.quote(str(target))}

2. Edit README.md
   Describe what the project is, its purpose and its main constraints.

3. Edit ROADMAP.md
   Define the first milestone, objective and expected outcomes.

4. Edit aido.yaml
   Define the first executable MVP:
   - objective
   - acceptance criteria
   - work items
   - QA commands

5. Validate (after completing Git setup if needed):
   aido validate

6. Commit your project definition:
   git add README.md ROADMAP.md aido.yaml
   git commit -m "Define initial project"

7. Start governed development:
   aido run

No development has been started.
""")
    return 0 if git_ready else 1


def _relpath(target: Path, base: Path) -> str:
    import os

    return os.path.relpath(target, base)


# --- aido validate -------------------------------------------------------

def _cmd_validate(args: argparse.Namespace) -> int:
    config = _load_config(args.config)
    if config is None:
        return 1

    registry = config.load_worker_registry()
    enabled = registry.enabled_workers()
    providers = sorted({w.provider for w in enabled})

    print(f"project: {config.project.id} ({config.project.name})")
    print(f"workspace: {config.project.workspace}")
    print(f"state_dir: {config.project.state_dir}")
    print(f"mvp: {config.mvp.id}")
    print(f"work_items: {len(config.work_items)}")
    print(f"qa_commands: {len(config.qa_commands)}")
    print(f"enabled_workers: {len(enabled)}")
    print(f"providers: {', '.join(providers) if providers else '(none)'}")
    print(f"permission_mode: {config.execution.permission_mode.value.upper()}")
    print(f"base_branch: {config.git.base_branch}")
    print("aido validate: OK")
    return 0


# --- aido status -----------------------------------------------------------

def _cmd_status(args: argparse.Namespace) -> int:
    """STRICTLY READ-ONLY *unless* ``--probe`` is explicitly given: never
    creates ``state_dir`` or any store file, never runs ``CREATE TABLE``/a
    migration, never writes a row — see ``OrchestratorEngine.status()``.
    Never uses the write-capable ``ProjectRuntime.open()`` composition (no
    QuotaManager/ProviderAdapter/WorkerSelector/RalphExecutionEngine/
    InternalQAEngine/GitGovernanceService are ever instantiated unless
    ``--probe`` is set, and even then only ``OrchestratorEngine.
    probe_workers()``'s own, already-tested QuotaManager/ProviderAdapter
    composition — never a second one built here). One ``OrchestratorEngine``
    is built and reused for both ``.status()`` and (if requested)
    ``.probe_workers()`` — never a second, independent traversal of
    persisted state built directly in this module (REUSE FIRST, AUD-4)."""
    config = _load_config(args.config)
    if config is None:
        return 1

    try:
        registry = config.load_worker_registry()
    except WorkerRegistryError as exc:
        print(f"aido: invalid worker registry — {exc}", file=sys.stderr)
        return 1

    engine = OrchestratorEngine(config, provider_adapters=getattr(args, "provider_adapters", None))
    _print_project_status(engine)

    probes: tuple[Any, ...] | None = None
    if getattr(args, "probe", False):
        try:
            probes = engine.probe_workers()
        except EngineConfigError as exc:
            print(f"aido status --probe: FAIL — {exc}", file=sys.stderr)
            return 1

    print()
    _print_workers_section(registry, probes)

    if probes is not None:
        print()
        _print_provider_quotas_section(probes)

    return 0


def _print_project_status(engine: OrchestratorEngine) -> None:
    """Pure rendering over ``OrchestratorEngine.status()``'s own
    ``ProjectStatusSnapshot`` — the exact same real, read-only status path
    exposed to any other frontend (P13, e.g. AIDO Code), never a second,
    independent traversal of ``ProjectStatusReader`` built here (REUSE
    FIRST, AUD-4). A genuine read failure (corrupted state, I/O error, ...)
    propagates rather than being folded into ``NOT_INITIALIZED`` (AUD-3):
    only ``OrchestratorEngine.status()``'s own explicit, typed
    "project truly never bootstrapped" case renders that message."""
    snapshot = engine.status()
    if not snapshot.initialized:
        print("NOT_INITIALIZED")
        print("Run `aido run` to initialize and start this project.")
        return

    print(f"project: {snapshot.project_id} ({snapshot.project_name})")
    mvp = snapshot.mvp
    if mvp is None or mvp.status is None:
        print(f"mvp: {mvp.mvp_id if mvp is not None else '?'} (not yet created)")
    else:
        print(f"mvp: {mvp.mvp_id} status={mvp.status}")

    counts = {status: 0 for status in WorkItemStatus}
    for wi in snapshot.work_items:
        counts[WorkItemStatus(wi.status)] += 1
        line = f"  {wi.work_item_id}: {wi.status}"
        if wi.blocked_reason:
            line += f" (blocked_reason={wi.blocked_reason})"
        print(line)

        if wi.last_execution is not None:
            last = wi.last_execution
            worker_label = (
                f"{last.worker_display_name} [{last.worker_id}]"
                if last.worker_display_name else f"{last.worker_id} [unknown display name]"
            )
            print(
                f"      last execution: worker={worker_label} provider={last.provider} "
                f"status={last.status} "
                f"permission_mode={last.permission_mode or 'unknown'}"
            )
        if wi.wait is not None:
            print(
                f"      wait: phase={wi.wait.phase} "
                f"eligible_at={wi.wait.eligible_at} "
                f"providers={','.join(wi.wait.providers) or '(any)'}"
            )

    print("\nWorkItem status counts:")
    for status in _REPORTED_STATUSES:
        print(f"  {status.value}: {counts[status]}")


def _print_workers_section(registry: "WorkerRegistry", probes: "tuple[Any, ...] | None") -> None:
    """Shared by ``aido status``/``aido status --probe``: one rendering
    path for the worker list, never duplicated between the two modes.
    ``probes`` is ``None`` for the no-probe case (no ``probe=`` line at
    all); otherwise each worker's line gets the observable state of ITS
    OWN provider (never a fabricated per-worker state — two workers on
    the same provider show the exact same probe result, see ROADMAP.md)."""
    by_provider = {p.provider: p for p in (probes or ())}
    print("Workers:")
    for worker in registry.all_workers():
        state = "enabled" if worker.enabled else "disabled"
        line = (
            f"  {worker.worker_id} — {worker.display_name}\n"
            f"    {state}\n"
            f"    provider={worker.provider}\n"
            f"    backend={worker.backend}\n"
            f"    model={worker.profile().model}"
        )
        print(line)
        if probes is not None:
            if not worker.enabled:
                # A disabled worker's provider is never probed at all
                # (probe_workers() only probes enabled workers' providers)
                # — "disabled" is the honest fact here, never a fabricated
                # "unknown" that implies a probe was attempted.
                probe_state = "disabled"
            else:
                snapshot = by_provider.get(worker.provider)
                probe_state = snapshot.reason if snapshot is not None else "unknown"
            print(f"    probe={probe_state}")


def _print_provider_quotas_section(probes: "tuple[Any, ...]") -> None:
    """Quota is a PROVIDER-level fact, never per-worker (ROADMAP.md): one
    block per distinct provider actually probed, regardless of how many
    workers share it."""
    print("Provider quotas:")
    for snapshot in sorted(probes, key=lambda p: p.provider):
        print(f"  {snapshot.provider}:")
        if not snapshot.quota_windows:
            print("    quota: unknown")
        for window in snapshot.quota_windows:
            used = f"{window.utilization:.0%}" if window.utilization is not None else "unknown"
            remaining = f"{window.remaining:.0%}" if window.remaining is not None else "unknown"
            reset = window.reset_at or "unknown"
            print(f"    {window.window_type}:")
            print(f"      used: {used}")
            print(f"      remaining: {remaining}")
            print(f"      reset: {reset}")
        if snapshot.reset_credits:
            print("    reset credits:")
            for credit in snapshot.reset_credits:
                count = credit.available_count if credit.available_count is not None else "unknown"
                print(f"      {credit.title}: {credit.status} (available: {count})")


# --- aido run --------------------------------------------------------------

def _cmd_run(args: argparse.Namespace) -> int:
    config = _load_config(args.config)
    if config is None:
        return 1

    if config.execution.permission_mode is ExecutionPermissionMode.UNRESTRICTED:
        print("WARNING: project requests UNRESTRICTED worker execution permissions.")

    try:
        runtime = ProjectRuntime.open(
            config,
            clock=getattr(args, "clock", None),
            provider_adapters=getattr(args, "provider_adapters", None),
            subprocess_runner=getattr(args, "subprocess_runner", None),
        )
    except ProjectRuntimeError as exc:
        print(f"aido run: FAIL — {exc}", file=sys.stderr)
        return 1

    try:
        try:
            runtime.bootstrap()
        except ConfigRuntimeConflictError as exc:
            print(f"aido run: FAIL — {exc}", file=sys.stderr)
            return 1

        cycles_run = 0
        for cycle in range(1, args.max_cycles + 1):
            cycles_run = cycle
            result = asyncio.run(runtime.manager.run_next_work_item(config.mvp.id))
            if result is None:
                print("aido run: nothing currently eligible/due.")
                break

            line = f"{result.work_item.work_item_id} -> {result.work_item.status.value}"
            if result.work_item.blocked_reason:
                line += f" ({result.work_item.blocked_reason})"
            print(line)
            if result.work_item.status is WorkItemStatus.WAITING and result.wait is not None:
                print(
                    f"  WAITING: phase={result.wait.phase.value} "
                    f"eligible_at={result.wait.eligible_at} "
                    f"providers={','.join(result.wait.providers) or '(any)'}"
                )

            all_terminal = all(
                wi.status in _TERMINAL_STATUSES
                for wi in runtime.project_store.list_work_items(config.mvp.id)
            )
            if all_terminal:
                break
        else:
            print(f"aido run: reached --max-cycles={args.max_cycles} — re-run `aido run` to continue.")

        final_items = sorted(
            runtime.project_store.list_work_items(config.mvp.id), key=lambda w: w.work_item_id
        )
        print("\n=== summary ===")
        for wi in final_items:
            print(f"  {wi.work_item_id}: {wi.status.value}")
        all_terminal = all(wi.status in _TERMINAL_STATUSES for wi in final_items)
        print(f"cycles_run={cycles_run} all_terminal={all_terminal}")
        print(
            "Re-running `aido run` against the same config resumes this project "
            "from its persisted state — there is no separate resume command."
        )
        return 0
    finally:
        runtime.close()


# --- argument parsing --------------------------------------------------------

_SHORT_DESCRIPTION = (
    "Operate an AI Dev Orchestrator-governed project from an aido.yaml — "
    "no custom Python harness required. See docs/PROJECT_CONFIG.md for "
    "the config schema."
)


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="aido", description=_SHORT_DESCRIPTION)
    subparsers = parser.add_subparsers(dest="command", required=True)

    init_parser = subparsers.add_parser("init", help="Create a project, or write a starting aido.yaml template.")
    init_parser.add_argument("config", nargs="?", default=DEFAULT_CONFIG_PATH,
                             metavar="config-or-parent", help="Legacy config path, or new project's parent.")
    init_parser.add_argument("new_project", nargs="?", metavar="project-name",
                             help="Create a complete project under the parent path.")
    init_parser.add_argument("--workers-registry", default=None)
    init_parser.add_argument("--project-id", default=None)
    init_parser.add_argument("--project-name", default=None)
    init_parser.add_argument("--workspace", default=None)
    init_parser.add_argument(
        "--permission-mode", choices=[m.value for m in ExecutionPermissionMode], default=None,
    )
    init_parser.set_defaults(func=_cmd_init)

    validate_parser = subparsers.add_parser("validate", help="Load/validate a config, print facts.")
    validate_parser.add_argument("config", nargs="?", default=DEFAULT_CONFIG_PATH)
    validate_parser.set_defaults(func=_cmd_validate)

    run_parser = subparsers.add_parser(
        "run", help="Bootstrap (idempotent) and drive WorkItem Flow. Also the resume operation.",
    )
    run_parser.add_argument("config", nargs="?", default=DEFAULT_CONFIG_PATH)
    run_parser.add_argument("--max-cycles", type=int, default=DEFAULT_MAX_CYCLES)
    run_parser.set_defaults(func=_cmd_run)

    status_parser = subparsers.add_parser("status", help="Read persisted state — no provider calls.")
    status_parser.add_argument("config", nargs="?", default=DEFAULT_CONFIG_PATH)
    status_parser.add_argument(
        "--probe", action="store_true",
        help="Also perform one real, explicit provider probe (network/CLI). Omit for zero provider calls.",
    )
    status_parser.set_defaults(func=_cmd_status)

    return parser


def main(argv: list[str] | None = None) -> int:
    parser = _build_parser()
    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
