"""aido — the public AIDO CLI (P1).

Removes the need for a user to write a custom Python harness
(``scripts/run_external_project_pilot.py`` remains real implementation
evidence, not the product surface). Consumes ``ProjectConfig`` (P12) and
``ProjectRuntime`` — this module stays thin: argument parsing and plain-
text presentation only. It never composes stores/services itself and
never contains WorkItem-scheduling logic (``MVPManager`` stays
authoritative).

Four commands, deliberately no more (KISS/YAGNI):

- ``aido init``     — write a starting ``aido.yaml`` template.
- ``aido validate`` — load/validate a config, print facts, no side effects.
- ``aido run``      — bootstrap (idempotent) + drive WorkItem Flow to
  completion/WAITING/max-cycles. Also the resume operation — there is no
  separate ``aido resume``: re-running ``aido run`` against the same
  config reopens the same persisted state (``ProjectConfig.project.state_dir``)
  and continues via the existing WAITING/RECOVERY_REQUIRED mechanisms.
- ``aido status``   — read persisted state, no provider calls, no
  mutation.

Exit codes (deliberately simple):

- ``0``: the CLI operation itself completed successfully — including a
  project that is legitimately ``WAITING`` or has nothing currently due.
  ``WAITING`` is a valid durable orchestration state, never a CLI failure.
- ``1``: an operational/configuration failure — invalid config, a
  persisted-state/config conflict, provider/backend composition
  impossible, or an actual orchestration error.
- ``2``: usage error (argparse's own standard behavior).

Only ``aido run`` ever causes a real provider probe or worker execution.
``init``/``validate``/``status`` are provider-call-free by construction —
none of them ever call ``ProjectRuntime.open()`` and ``bootstrap()``
followed by ``MVPManager.run_next_work_item(...)``.
"""

from __future__ import annotations

import argparse
import asyncio
import re
import sys
from pathlib import Path

from orchestrator.execution_policy import ExecutionPermissionMode
from orchestrator.project_config import ProjectConfig, ProjectConfigError
from orchestrator.project_runtime import (
    ConfigRuntimeConflictError,
    ProjectRuntime,
    ProjectRuntimeError,
    ProjectStatusReader,
)
from orchestrator.project_state import UnknownMVPError, WorkItemStatus
from orchestrator.worker_registry import WorkerRegistryError

DEFAULT_CONFIG_PATH = "./aido.yaml"
DEFAULT_MAX_CYCLES = 50

_TERMINAL_STATUSES = frozenset(
    {WorkItemStatus.COMPLETED, WorkItemStatus.FAILED, WorkItemStatus.BLOCKED}
)
# Reported status counts — REVIEWING is legacy decode-only (see
# WorkItemStatus's own docstring), never a current WorkItem Flow phase,
# so it is deliberately excluded from this user-facing summary.
_REPORTED_STATUSES = tuple(s for s in WorkItemStatus if s is not WorkItemStatus.REVIEWING)


def _yaml_str(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _sanitize_id(name: str) -> str:
    slug = re.sub(r"[^a-z0-9-]+", "-", name.lower()).strip("-")
    return slug or "project"


def _load_config(path: str) -> ProjectConfig | None:
    """Loads a config, printing one clean line (never a traceback) for an
    ordinary bad config/worker-registry problem."""
    try:
        return ProjectConfig.load(path)
    except (ProjectConfigError, WorkerRegistryError) as exc:
        print(f"aido: invalid project configuration — {exc}", file=sys.stderr)
        return None


# --- aido init ---------------------------------------------------------

_INIT_TEMPLATE = """\
# Generated by `aido init` — EDIT ME before running `aido validate`/`aido run`.
# See docs/PROJECT_CONFIG.md for the full schema reference.

schema_version: 1

project:
  id: {project_id}
  name: {project_name}
  workspace: {workspace}
  # state_dir omitted on purpose — defaults deterministically to
  # ~/.local/state/ai-dev-orchestrator/projects/{project_id_raw}/

workers:
  registry: {registry}

execution:
  permission_mode: {permission_mode}

git:
  base_branch: main

mvp:
  id: mvp-1
  objective: "TODO: describe the first governed slice of real product work."
  acceptance_criteria:
    - "TODO: state, concretely, what 'done' means for this MVP."

work_items:
  # EXAMPLE WorkItem template — AIDO cannot infer your acceptance
  # criteria automatically. Replace this with your own WorkItem(s).
  - id: wi-1
    title: "TODO: describe the first WorkItem"
    required_capabilities: [development]
    dependencies: []
    acceptance_criteria:
      - "TODO: state, concretely, what 'done' means for this WorkItem."

qa:
  # A common default, only if your project actually uses pytest —
  # replace or remove this if it does not. AIDO never guesses your real
  # QA commands beyond this one safe, widely-applicable template.
  - id: qa-tests
    kind: unit_test
    argv: ["pytest", "-q"]
    timeout_seconds: 300
    required: true
"""


def _cmd_init(args: argparse.Namespace) -> int:
    config_path = Path(args.config).expanduser().resolve()
    if config_path.exists():
        print(f"aido init: {config_path} already exists — refusing to overwrite.", file=sys.stderr)
        return 1

    if args.workers_registry:
        registry_path = Path(args.workers_registry).expanduser().resolve()
    else:
        candidate = Path.cwd() / "config" / "workers.yaml"
        if not candidate.is_file():
            print(
                "aido init: --workers-registry is required (no config/workers.yaml "
                "found in the current directory to resolve automatically).",
                file=sys.stderr,
            )
            return 1
        registry_path = candidate.resolve()
        print(f"aido init: no --workers-registry given; using existing {registry_path}")

    if not registry_path.is_file():
        print(f"aido init: worker registry not found: {registry_path}", file=sys.stderr)
        return 1
    try:
        from orchestrator.worker_registry import WorkerRegistry

        WorkerRegistry.load(registry_path)
    except WorkerRegistryError as exc:
        print(f"aido init: invalid worker registry {registry_path}: {exc}", file=sys.stderr)
        return 1

    config_dir = config_path.parent
    workspace_path = Path(args.workspace).expanduser().resolve() if args.workspace else config_dir
    try:
        workspace_rel = Path(_relpath(workspace_path, config_dir))
    except ValueError:
        workspace_rel = workspace_path
    try:
        registry_rel = Path(_relpath(registry_path, config_dir))
    except ValueError:
        registry_rel = registry_path

    project_id = args.project_id or _sanitize_id(workspace_path.name)
    project_name = args.project_name or workspace_path.name
    permission_mode = args.permission_mode or ExecutionPermissionMode.STANDARD.value

    content = _INIT_TEMPLATE.format(
        project_id=_yaml_str(project_id),
        project_id_raw=project_id,
        project_name=_yaml_str(project_name),
        workspace=_yaml_str(str(workspace_rel)),
        registry=_yaml_str(str(registry_rel)),
        permission_mode=permission_mode,
    )
    config_path.write_text(content)
    print(f"aido init: wrote {config_path}")
    print("Edit it — especially mvp.objective/acceptance_criteria and work_items "
          "— then run `aido validate`.")
    return 0


def _relpath(target: Path, base: Path) -> str:
    import os

    return os.path.relpath(target, base)


# --- aido validate -------------------------------------------------------

def _cmd_validate(args: argparse.Namespace) -> int:
    config = _load_config(args.config)
    if config is None:
        return 1

    registry = config.load_worker_registry()
    enabled = registry.enabled_workers()
    providers = sorted({w.provider for w in enabled})

    print(f"project: {config.project.id} ({config.project.name})")
    print(f"workspace: {config.project.workspace}")
    print(f"state_dir: {config.project.state_dir}")
    print(f"mvp: {config.mvp.id}")
    print(f"work_items: {len(config.work_items)}")
    print(f"qa_commands: {len(config.qa_commands)}")
    print(f"enabled_workers: {len(enabled)}")
    print(f"providers: {', '.join(providers) if providers else '(none)'}")
    print(f"permission_mode: {config.execution.permission_mode.value.upper()}")
    print(f"base_branch: {config.git.base_branch}")
    print("aido validate: OK")
    return 0


# --- aido status -----------------------------------------------------------

def _cmd_status(args: argparse.Namespace) -> int:
    """STRICTLY READ-ONLY: never creates ``state_dir`` or any store file,
    never runs ``CREATE TABLE``/a migration, never writes a row — see
    ``ProjectStatusReader``. Never uses the write-capable
    ``ProjectRuntime.open()`` composition (no QuotaManager/
    ProviderAdapter/WorkerSelector/RalphExecutionEngine/InternalQAEngine/
    GitGovernanceService are ever instantiated for this command)."""
    config = _load_config(args.config)
    if config is None:
        return 1

    reader = ProjectStatusReader.open(config)
    if reader is None:
        print("NOT_INITIALIZED")
        print("Run `aido run` to initialize and start this project.")
        return 0

    try:
        try:
            project = reader.project_store.get_project(config.project.id)
        except Exception:
            print("NOT_INITIALIZED")
            print("Run `aido run` to initialize and start this project.")
            return 0

        print(f"project: {project.project_id} ({project.name})")
        try:
            mvp = reader.project_store.get_mvp(config.mvp.id)
            print(f"mvp: {mvp.mvp_id} status={mvp.status.value}")
        except UnknownMVPError:
            print(f"mvp: {config.mvp.id} (not yet created)")
            print("\nWorkItem status counts:")
            for status in _REPORTED_STATUSES:
                print(f"  {status.value}: 0")
            return 0

        work_items = sorted(
            reader.project_store.list_work_items(config.mvp.id), key=lambda w: w.work_item_id
        )
        waits = reader.list_waits_for_mvp(config.mvp.id)

        counts = {status: 0 for status in WorkItemStatus}
        for wi in work_items:
            counts[wi.status] += 1
            line = f"  {wi.work_item_id}: {wi.status.value}"
            if wi.blocked_reason:
                line += f" (blocked_reason={wi.blocked_reason})"
            print(line)

            executions = reader.list_executions_for_work_item(wi.work_item_id)
            if executions:
                last = executions[-1]
                print(
                    f"      last execution: worker={last.worker_id} provider={last.provider} "
                    f"status={last.status.value} "
                    f"permission_mode={last.permission_mode or 'unknown'}"
                )
            item_waits = [w for w in waits if w.work_item_id == wi.work_item_id]
            if item_waits:
                latest_wait = max(item_waits, key=lambda w: w.created_at)
                print(
                    f"      wait: phase={latest_wait.phase.value} "
                    f"eligible_at={latest_wait.eligible_at} "
                    f"providers={','.join(latest_wait.providers) or '(any)'}"
                )

        print("\nWorkItem status counts:")
        for status in _REPORTED_STATUSES:
            print(f"  {status.value}: {counts[status]}")
        return 0
    finally:
        reader.close()


# --- aido run --------------------------------------------------------------

def _cmd_run(args: argparse.Namespace) -> int:
    config = _load_config(args.config)
    if config is None:
        return 1

    if config.execution.permission_mode is ExecutionPermissionMode.UNRESTRICTED:
        print("WARNING: project requests UNRESTRICTED worker execution permissions.")

    try:
        runtime = ProjectRuntime.open(
            config,
            clock=getattr(args, "clock", None),
            provider_adapters=getattr(args, "provider_adapters", None),
            subprocess_runner=getattr(args, "subprocess_runner", None),
        )
    except ProjectRuntimeError as exc:
        print(f"aido run: FAIL — {exc}", file=sys.stderr)
        return 1

    try:
        try:
            runtime.bootstrap()
        except ConfigRuntimeConflictError as exc:
            print(f"aido run: FAIL — {exc}", file=sys.stderr)
            return 1

        cycles_run = 0
        for cycle in range(1, args.max_cycles + 1):
            cycles_run = cycle
            result = asyncio.run(runtime.manager.run_next_work_item(config.mvp.id))
            if result is None:
                print("aido run: nothing currently eligible/due.")
                break

            line = f"{result.work_item.work_item_id} -> {result.work_item.status.value}"
            if result.work_item.blocked_reason:
                line += f" ({result.work_item.blocked_reason})"
            print(line)
            if result.work_item.status is WorkItemStatus.WAITING and result.wait is not None:
                print(
                    f"  WAITING: phase={result.wait.phase.value} "
                    f"eligible_at={result.wait.eligible_at} "
                    f"providers={','.join(result.wait.providers) or '(any)'}"
                )

            all_terminal = all(
                wi.status in _TERMINAL_STATUSES
                for wi in runtime.project_store.list_work_items(config.mvp.id)
            )
            if all_terminal:
                break
        else:
            print(f"aido run: reached --max-cycles={args.max_cycles} — re-run `aido run` to continue.")

        final_items = sorted(
            runtime.project_store.list_work_items(config.mvp.id), key=lambda w: w.work_item_id
        )
        print("\n=== summary ===")
        for wi in final_items:
            print(f"  {wi.work_item_id}: {wi.status.value}")
        all_terminal = all(wi.status in _TERMINAL_STATUSES for wi in final_items)
        print(f"cycles_run={cycles_run} all_terminal={all_terminal}")
        print(
            "Re-running `aido run` against the same config resumes this project "
            "from its persisted state — there is no separate resume command."
        )
        return 0
    finally:
        runtime.close()


# --- argument parsing --------------------------------------------------------

_SHORT_DESCRIPTION = (
    "Operate an AI Dev Orchestrator-governed project from an aido.yaml — "
    "no custom Python harness required. See docs/PROJECT_CONFIG.md for "
    "the config schema."
)


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="aido", description=_SHORT_DESCRIPTION)
    subparsers = parser.add_subparsers(dest="command", required=True)

    init_parser = subparsers.add_parser("init", help="Write a starting aido.yaml template.")
    init_parser.add_argument("config", nargs="?", default=DEFAULT_CONFIG_PATH)
    init_parser.add_argument("--workers-registry", default=None)
    init_parser.add_argument("--project-id", default=None)
    init_parser.add_argument("--project-name", default=None)
    init_parser.add_argument("--workspace", default=None)
    init_parser.add_argument(
        "--permission-mode", choices=[m.value for m in ExecutionPermissionMode], default=None,
    )
    init_parser.set_defaults(func=_cmd_init)

    validate_parser = subparsers.add_parser("validate", help="Load/validate a config, print facts.")
    validate_parser.add_argument("config", nargs="?", default=DEFAULT_CONFIG_PATH)
    validate_parser.set_defaults(func=_cmd_validate)

    run_parser = subparsers.add_parser(
        "run", help="Bootstrap (idempotent) and drive WorkItem Flow. Also the resume operation.",
    )
    run_parser.add_argument("config", nargs="?", default=DEFAULT_CONFIG_PATH)
    run_parser.add_argument("--max-cycles", type=int, default=DEFAULT_MAX_CYCLES)
    run_parser.set_defaults(func=_cmd_run)

    status_parser = subparsers.add_parser("status", help="Read persisted state — no provider calls.")
    status_parser.add_argument("config", nargs="?", default=DEFAULT_CONFIG_PATH)
    status_parser.set_defaults(func=_cmd_status)

    return parser


def main(argv: list[str] | None = None) -> int:
    parser = _build_parser()
    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
