"""Realization reports — a detailed, auditable snapshot of one WorkItem's
realization (Slice 18).

Answers "what actually happened to this WorkItem, in order, and why?" —
distinct from :mod:`~orchestrator.activity_report`, which stays a
release/MVP-level consolidation. A ``RealizationReport`` is finer-grained:
one WorkItem, every pre-flight/recommendation/adaptive decision/execution/
handoff/wait/validation/review it ever went through, in chronological
order. ``ActivityReport`` may reference ``realization_report_id``s later;
this module never duplicates or replaces it.

SOURCE OF TRUTH IS NEVER THE HTML: a ``RealizationReport`` is a pure,
deterministic aggregation of already-persisted facts read from
``ProjectStateStore``/``ExecutionStore``/``HandoffStore``/
``ValidationStore``/``ReviewStore``/``WaitStore``/
``ExecutionRecommendationStore``/``AdaptiveExecutionDecisionStore`` — never
invented, never LLM-authored. ``render_html()`` is a pure, structure-to-text
projection of an already-built ``RealizationReport``; nothing in this
codebase is ever allowed to parse that HTML back into state — a future
worker may be handed the HTML (or the report) as extra *context*, but
``HandoffRecord`` remains the one canonical, machine-readable passation
artifact (see ``orchestrator.handoff``).

IMMUTABLE, INSERT-ONLY: a ``RealizationReport`` is a snapshot at
``generated_at`` — it is never updated in place. Generating again (e.g.
after a handoff, or after final completion) always produces a new
``report_id``; the previous report is kept forever, exactly like
``PlannerProposal``/``RoadmapApplication``/``ExecutionRecommendation``
before it. This is what makes an intermediate report usable as a durable
passation artifact: a caller can trust that a report it saw once will
never change under it.

DETERMINISTIC SUMMARY, NEVER AN LLM: the human-readable summary at the top
of the report (and the whole render) is built by small, explicit rules
over the aggregated facts (see ``_build_summary_text``/``_derive_status``)
— never generated by a worker.
"""

from __future__ import annotations

import hashlib
import html as html_lib
import json
import os
import sqlite3
import tempfile
import uuid
from dataclasses import dataclass
from datetime import datetime, timezone
from enum import Enum
from pathlib import Path
from typing import Callable

from orchestrator.execution_store import ExecutionRecord, ExecutionStatus, ExecutionStore
from orchestrator.handoff import HandoffRecord, HandoffStore
from orchestrator.project_state import ProjectStateStore, WorkItem, WorkItemStatus

Clock = Callable[[], datetime]
IdFactory = Callable[[], str]


def _default_id_factory() -> str:
    return uuid.uuid4().hex


def _require_non_empty_str(value: object, *, field_name: str) -> None:
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"{field_name} must be a non-empty string, got {value!r}")


def _require_aware(moment: datetime, *, field_name: str) -> None:
    if not isinstance(moment, datetime) or moment.tzinfo is None or moment.tzinfo.utcoffset(moment) is None:
        raise ValueError(f"{field_name} must be a timezone-aware datetime, got {moment!r}")


class RealizationReportStatus(str, Enum):
    """The report's own status — distinct from ``WorkItemStatus``: a
    thin, deterministic projection of it plus "is a handoff available for
    passation right now" (see ``_derive_status``)."""

    IN_PROGRESS = "in_progress"
    HANDOFF_READY = "handoff_ready"
    COMPLETED = "completed"
    BLOCKED = "blocked"
    FAILED = "failed"


# --- timeline entry type vocabulary (extensible, not a strict enum) --------

TIMELINE_RECOMMENDATION = "recommendation"
TIMELINE_ADAPTIVE_DECISION = "adaptive_decision"
TIMELINE_EXECUTION_STARTED = "execution_started"
TIMELINE_EXECUTION_FINISHED = "execution_finished"
TIMELINE_WAIT_STARTED = "wait_started"
TIMELINE_WAIT_RESOLVED = "wait_resolved"
TIMELINE_HANDOFF = "handoff"
TIMELINE_VALIDATION = "validation"
TIMELINE_REVIEW_STARTED = "review_started"
TIMELINE_REVIEW_FINISHED = "review_finished"
# Git governance (Slice 20) audit events, reused verbatim from
# ``GitWorkItemStore.list_events`` — never a re-derivation from raw git
# log, just a projection of the already-persisted, structured audit trail.
TIMELINE_GIT_BRANCH_PREPARED = "branch_prepared"
TIMELINE_GIT_HEAD_CAPTURED = "head_captured"
TIMELINE_GIT_MERGE_READY = "merge_ready"
TIMELINE_GIT_MERGED = "merged"
TIMELINE_GIT_MERGE_CONFLICT = "merge_conflict"


@dataclass(frozen=True, slots=True)
class TimelineEntry:
    timestamp: datetime
    entry_type: str
    summary: str
    references: tuple[str, ...] = ()

    def __post_init__(self) -> None:
        _require_aware(self.timestamp, field_name="TimelineEntry.timestamp")
        _require_non_empty_str(self.entry_type, field_name="TimelineEntry.entry_type")
        _require_non_empty_str(self.summary, field_name="TimelineEntry.summary")
        object.__setattr__(self, "references", tuple(self.references))


@dataclass(frozen=True, slots=True)
class ExecutionEntry:
    execution_id: str
    role: str
    worker_id: str
    provider: str
    backend: str
    model: str
    started_at: datetime
    status: str
    reasoning_effort: str | None = None
    finished_at: datetime | None = None
    exit_code: int | None = None
    provider_session_id: str | None = None
    ralph_loop_id: str | None = None
    git_sha_before: str | None = None
    git_sha_after: str | None = None


@dataclass(frozen=True, slots=True)
class RecommendationEntry:
    recommendation_id: str
    role: str
    estimator_worker_id: str
    estimator_execution_id: str
    estimator_profile_id: str
    task_fingerprint: str
    minimum_quality_tier: str
    reasons: tuple[str, ...]
    created_at: datetime
    recommended_reasoning: str | None = None


@dataclass(frozen=True, slots=True)
class DecisionEntry:
    decision_id: str
    recommendation_id: str
    role: str
    worker_id: str
    provider: str
    backend: str
    profile_id: str
    quality_tier: str
    model: str
    created_at: datetime
    reasoning_effort: str | None = None
    rationale: str = ""


@dataclass(frozen=True, slots=True)
class HandoffEntry:
    handoff_id: str
    created_at: datetime
    execution_id: str | None = None
    worker_id: str | None = None
    completed_work: str | None = None
    decisions: str | None = None
    files_touched: tuple[str, ...] = ()
    tests_run: tuple[str, ...] = ()
    test_results: str | None = None
    open_issues: str | None = None
    risks: str | None = None
    next_action: str | None = None
    git_sha_after: str | None = None


@dataclass(frozen=True, slots=True)
class ValidationEntry:
    validation_run_id: str
    validation_id: str
    kind: str
    required: bool
    status: str
    started_at: datetime
    duration_ms: int
    exit_code: int | None = None
    git_sha: str | None = None


@dataclass(frozen=True, slots=True)
class ReviewEntry:
    review_id: str
    author_worker_id: str
    status: str
    started_at: datetime
    finished_at: datetime
    reviewer_worker_id: str | None = None
    findings_summary: tuple[str, ...] = ()


@dataclass(frozen=True, slots=True)
class WaitEntry:
    wait_id: str
    phase: str
    reason: str
    created_at: datetime
    eligible_at: datetime
    status: str
    resolved_at: datetime | None = None
    resolution: str | None = None


@dataclass(frozen=True, slots=True)
class RealizationReport:
    """A durable, immutable snapshot of one WorkItem's realization —
    never updated in place; a later generation is always a new report."""

    report_id: str
    project_id: str
    mvp_id: str
    work_item_id: str
    generated_at: datetime
    report_status: RealizationReportStatus
    final_work_item_status: str
    objective: str
    summary_text: str
    acceptance_criteria: tuple[str, ...] = ()
    dependencies: tuple[str, ...] = ()
    git_sha_initial: str | None = None
    git_sha_final: str | None = None
    git_base_branch: str | None = None
    git_work_branch: str | None = None
    git_merge_status: str | None = None
    git_merged_sha: str | None = None
    git_pull_request_number: int | None = None
    git_pull_request_url: str | None = None
    qa_run_id: str | None = None
    qa_engine_id: str | None = None
    qa_phase: str | None = None
    qa_verdict_status: str | None = None
    qa_expected_head_sha: str | None = None
    qa_observed_head_sha: str | None = None
    qa_tests_executed_count: int | None = None
    qa_passed_count: int | None = None
    qa_failed_count: int | None = None
    qa_regressions: tuple[str, ...] = ()
    executions: tuple[ExecutionEntry, ...] = ()
    recommendations: tuple[RecommendationEntry, ...] = ()
    decisions: tuple[DecisionEntry, ...] = ()
    handoffs: tuple[HandoffEntry, ...] = ()
    validations: tuple[ValidationEntry, ...] = ()
    reviews: tuple[ReviewEntry, ...] = ()
    waits: tuple[WaitEntry, ...] = ()
    incidents: tuple[str, ...] = ()
    timeline: tuple[TimelineEntry, ...] = ()

    def __post_init__(self) -> None:
        for name in ("report_id", "project_id", "mvp_id", "work_item_id", "objective", "final_work_item_status", "summary_text"):
            _require_non_empty_str(getattr(self, name), field_name=f"RealizationReport.{name}")
        if not isinstance(self.report_status, RealizationReportStatus):
            raise TypeError(f"RealizationReport.report_status must be a RealizationReportStatus, got {type(self.report_status)!r}")
        _require_aware(self.generated_at, field_name="RealizationReport.generated_at")

    def render_html(self) -> str:
        return _render_html(self)


def compute_html_hash(html: str) -> str:
    """A deterministic content hash of a rendered report — the same
    ``RealizationReport`` always renders to the exact same bytes."""
    return hashlib.sha256(html.encode("utf-8")).hexdigest()


def write_html(report: RealizationReport, output_path: str | Path) -> Path:
    """Atomically writes ``report.render_html()`` to ``output_path``.

    ``output_path`` is entirely caller-supplied — this module never
    hardcodes a project path; a caller wanting the
    ``reports/realizations/<work_item_id>/<report_id>.html`` convention
    builds that path itself before calling this.
    """
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    html = report.render_html()
    fd, tmp_name = tempfile.mkstemp(dir=str(path.parent), prefix=f".{path.name}.", suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(html)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(tmp_name, path)
    except BaseException:
        try:
            os.unlink(tmp_name)
        except OSError:
            pass
        raise
    return path


# --- persistence -------------------------------------------------------------


class RealizationReportStoreError(Exception):
    """Base for RealizationReportStore domain errors."""


class UnknownRealizationReportError(RealizationReportStoreError):
    def __init__(self, report_id: str) -> None:
        super().__init__(f"unknown realization report: {report_id!r}")
        self.report_id = report_id


class DuplicateRealizationReportError(RealizationReportStoreError):
    def __init__(self, report_id: str) -> None:
        super().__init__(f"realization report already exists: {report_id!r}")
        self.report_id = report_id


class CorruptRealizationReportError(RealizationReportStoreError):
    def __init__(self, report_id: str, detail: str) -> None:
        super().__init__(f"corrupt realization report {report_id!r}: {detail}")
        self.report_id = report_id


_CREATE_TABLE_SQL = """
CREATE TABLE IF NOT EXISTS realization_reports (
    report_id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    mvp_id TEXT NOT NULL,
    work_item_id TEXT NOT NULL,
    generated_at TEXT NOT NULL,
    report_status TEXT NOT NULL,
    final_work_item_status TEXT NOT NULL,
    payload TEXT NOT NULL
)
"""


def _encode_execution(e: ExecutionEntry) -> dict:
    return {
        "execution_id": e.execution_id, "role": e.role, "worker_id": e.worker_id, "provider": e.provider,
        "backend": e.backend, "model": e.model, "reasoning_effort": e.reasoning_effort,
        "started_at": e.started_at.isoformat(), "finished_at": e.finished_at.isoformat() if e.finished_at else None,
        "status": e.status, "exit_code": e.exit_code, "provider_session_id": e.provider_session_id,
        "ralph_loop_id": e.ralph_loop_id, "git_sha_before": e.git_sha_before, "git_sha_after": e.git_sha_after,
    }


def _decode_execution(d: dict) -> ExecutionEntry:
    return ExecutionEntry(
        execution_id=d["execution_id"], role=d["role"], worker_id=d["worker_id"], provider=d["provider"],
        backend=d["backend"], model=d["model"], reasoning_effort=d["reasoning_effort"],
        started_at=datetime.fromisoformat(d["started_at"]),
        finished_at=datetime.fromisoformat(d["finished_at"]) if d["finished_at"] else None,
        status=d["status"], exit_code=d["exit_code"], provider_session_id=d["provider_session_id"],
        ralph_loop_id=d["ralph_loop_id"], git_sha_before=d["git_sha_before"], git_sha_after=d["git_sha_after"],
    )


def _encode_recommendation(r: RecommendationEntry) -> dict:
    return {
        "recommendation_id": r.recommendation_id, "role": r.role, "estimator_worker_id": r.estimator_worker_id,
        "estimator_execution_id": r.estimator_execution_id, "estimator_profile_id": r.estimator_profile_id,
        "task_fingerprint": r.task_fingerprint, "minimum_quality_tier": r.minimum_quality_tier,
        "recommended_reasoning": r.recommended_reasoning, "reasons": list(r.reasons),
        "created_at": r.created_at.isoformat(),
    }


def _decode_recommendation(d: dict) -> RecommendationEntry:
    return RecommendationEntry(
        recommendation_id=d["recommendation_id"], role=d["role"], estimator_worker_id=d["estimator_worker_id"],
        estimator_execution_id=d["estimator_execution_id"], estimator_profile_id=d["estimator_profile_id"],
        task_fingerprint=d["task_fingerprint"], minimum_quality_tier=d["minimum_quality_tier"],
        recommended_reasoning=d["recommended_reasoning"], reasons=tuple(d["reasons"]),
        created_at=datetime.fromisoformat(d["created_at"]),
    )


def _encode_decision(dec: DecisionEntry) -> dict:
    return {
        "decision_id": dec.decision_id, "recommendation_id": dec.recommendation_id, "role": dec.role,
        "worker_id": dec.worker_id, "provider": dec.provider, "backend": dec.backend,
        "profile_id": dec.profile_id, "quality_tier": dec.quality_tier, "model": dec.model,
        "reasoning_effort": dec.reasoning_effort, "rationale": dec.rationale,
        "created_at": dec.created_at.isoformat(),
    }


def _decode_decision(d: dict) -> DecisionEntry:
    return DecisionEntry(
        decision_id=d["decision_id"], recommendation_id=d["recommendation_id"], role=d["role"],
        worker_id=d["worker_id"], provider=d["provider"], backend=d["backend"], profile_id=d["profile_id"],
        quality_tier=d["quality_tier"], model=d["model"], reasoning_effort=d["reasoning_effort"],
        rationale=d["rationale"], created_at=datetime.fromisoformat(d["created_at"]),
    )


def _encode_handoff(h: HandoffEntry) -> dict:
    return {
        "handoff_id": h.handoff_id, "created_at": h.created_at.isoformat(), "execution_id": h.execution_id,
        "worker_id": h.worker_id, "completed_work": h.completed_work, "decisions": h.decisions,
        "files_touched": list(h.files_touched), "tests_run": list(h.tests_run), "test_results": h.test_results,
        "open_issues": h.open_issues, "risks": h.risks, "next_action": h.next_action,
        "git_sha_after": h.git_sha_after,
    }


def _decode_handoff(d: dict) -> HandoffEntry:
    return HandoffEntry(
        handoff_id=d["handoff_id"], created_at=datetime.fromisoformat(d["created_at"]),
        execution_id=d["execution_id"], worker_id=d["worker_id"], completed_work=d["completed_work"],
        decisions=d["decisions"], files_touched=tuple(d["files_touched"]), tests_run=tuple(d["tests_run"]),
        test_results=d["test_results"], open_issues=d["open_issues"], risks=d["risks"],
        next_action=d["next_action"], git_sha_after=d["git_sha_after"],
    )


def _encode_validation(v: ValidationEntry) -> dict:
    return {
        "validation_run_id": v.validation_run_id, "validation_id": v.validation_id, "kind": v.kind,
        "required": v.required, "status": v.status, "started_at": v.started_at.isoformat(),
        "duration_ms": v.duration_ms, "exit_code": v.exit_code, "git_sha": v.git_sha,
    }


def _decode_validation(d: dict) -> ValidationEntry:
    return ValidationEntry(
        validation_run_id=d["validation_run_id"], validation_id=d["validation_id"], kind=d["kind"],
        required=d["required"], status=d["status"], started_at=datetime.fromisoformat(d["started_at"]),
        duration_ms=d["duration_ms"], exit_code=d["exit_code"], git_sha=d["git_sha"],
    )


def _encode_review(r: ReviewEntry) -> dict:
    return {
        "review_id": r.review_id, "author_worker_id": r.author_worker_id, "status": r.status,
        "started_at": r.started_at.isoformat(), "finished_at": r.finished_at.isoformat(),
        "reviewer_worker_id": r.reviewer_worker_id, "findings_summary": list(r.findings_summary),
    }


def _decode_review(d: dict) -> ReviewEntry:
    return ReviewEntry(
        review_id=d["review_id"], author_worker_id=d["author_worker_id"], status=d["status"],
        started_at=datetime.fromisoformat(d["started_at"]), finished_at=datetime.fromisoformat(d["finished_at"]),
        reviewer_worker_id=d["reviewer_worker_id"], findings_summary=tuple(d["findings_summary"]),
    )


def _encode_wait(w: WaitEntry) -> dict:
    return {
        "wait_id": w.wait_id, "phase": w.phase, "reason": w.reason, "created_at": w.created_at.isoformat(),
        "eligible_at": w.eligible_at.isoformat(), "status": w.status,
        "resolved_at": w.resolved_at.isoformat() if w.resolved_at else None, "resolution": w.resolution,
    }


def _decode_wait(d: dict) -> WaitEntry:
    return WaitEntry(
        wait_id=d["wait_id"], phase=d["phase"], reason=d["reason"], created_at=datetime.fromisoformat(d["created_at"]),
        eligible_at=datetime.fromisoformat(d["eligible_at"]), status=d["status"],
        resolved_at=datetime.fromisoformat(d["resolved_at"]) if d["resolved_at"] else None, resolution=d["resolution"],
    )


def _encode_timeline(t: TimelineEntry) -> dict:
    return {
        "timestamp": t.timestamp.isoformat(), "entry_type": t.entry_type, "summary": t.summary,
        "references": list(t.references),
    }


def _decode_timeline(d: dict) -> TimelineEntry:
    return TimelineEntry(
        timestamp=datetime.fromisoformat(d["timestamp"]), entry_type=d["entry_type"], summary=d["summary"],
        references=tuple(d["references"]),
    )


def _serialize(report: RealizationReport) -> str:
    return json.dumps({
        "report_id": report.report_id, "project_id": report.project_id, "mvp_id": report.mvp_id,
        "work_item_id": report.work_item_id, "generated_at": report.generated_at.isoformat(),
        "report_status": report.report_status.value, "final_work_item_status": report.final_work_item_status,
        "objective": report.objective, "summary_text": report.summary_text,
        "acceptance_criteria": list(report.acceptance_criteria), "dependencies": list(report.dependencies),
        "git_sha_initial": report.git_sha_initial, "git_sha_final": report.git_sha_final,
        "git_base_branch": report.git_base_branch, "git_work_branch": report.git_work_branch,
        "git_merge_status": report.git_merge_status, "git_merged_sha": report.git_merged_sha,
        "git_pull_request_number": report.git_pull_request_number,
        "git_pull_request_url": report.git_pull_request_url,
        "qa_run_id": report.qa_run_id, "qa_engine_id": report.qa_engine_id, "qa_phase": report.qa_phase,
        "qa_verdict_status": report.qa_verdict_status,
        "qa_expected_head_sha": report.qa_expected_head_sha, "qa_observed_head_sha": report.qa_observed_head_sha,
        "qa_tests_executed_count": report.qa_tests_executed_count, "qa_passed_count": report.qa_passed_count,
        "qa_failed_count": report.qa_failed_count, "qa_regressions": list(report.qa_regressions),
        "executions": [_encode_execution(e) for e in report.executions],
        "recommendations": [_encode_recommendation(r) for r in report.recommendations],
        "decisions": [_encode_decision(d) for d in report.decisions],
        "handoffs": [_encode_handoff(h) for h in report.handoffs],
        "validations": [_encode_validation(v) for v in report.validations],
        "reviews": [_encode_review(r) for r in report.reviews],
        "waits": [_encode_wait(w) for w in report.waits],
        "incidents": list(report.incidents),
        "timeline": [_encode_timeline(t) for t in report.timeline],
    })


def _deserialize(raw: str) -> RealizationReport:
    d = json.loads(raw)
    return RealizationReport(
        report_id=d["report_id"], project_id=d["project_id"], mvp_id=d["mvp_id"], work_item_id=d["work_item_id"],
        generated_at=datetime.fromisoformat(d["generated_at"]), report_status=RealizationReportStatus(d["report_status"]),
        final_work_item_status=d["final_work_item_status"], objective=d["objective"], summary_text=d["summary_text"],
        acceptance_criteria=tuple(d["acceptance_criteria"]), dependencies=tuple(d["dependencies"]),
        git_sha_initial=d["git_sha_initial"], git_sha_final=d["git_sha_final"],
        git_base_branch=d.get("git_base_branch"), git_work_branch=d.get("git_work_branch"),
        git_merge_status=d.get("git_merge_status"), git_merged_sha=d.get("git_merged_sha"),
        git_pull_request_number=d.get("git_pull_request_number"),
        git_pull_request_url=d.get("git_pull_request_url"),
        qa_run_id=d.get("qa_run_id"), qa_engine_id=d.get("qa_engine_id"), qa_phase=d.get("qa_phase"),
        qa_verdict_status=d.get("qa_verdict_status"),
        qa_expected_head_sha=d.get("qa_expected_head_sha"), qa_observed_head_sha=d.get("qa_observed_head_sha"),
        qa_tests_executed_count=d.get("qa_tests_executed_count"), qa_passed_count=d.get("qa_passed_count"),
        qa_failed_count=d.get("qa_failed_count"), qa_regressions=tuple(d.get("qa_regressions") or ()),
        executions=tuple(_decode_execution(e) for e in d["executions"]),
        recommendations=tuple(_decode_recommendation(r) for r in d["recommendations"]),
        decisions=tuple(_decode_decision(x) for x in d["decisions"]),
        handoffs=tuple(_decode_handoff(h) for h in d["handoffs"]),
        validations=tuple(_decode_validation(v) for v in d["validations"]),
        reviews=tuple(_decode_review(r) for r in d["reviews"]),
        waits=tuple(_decode_wait(w) for w in d["waits"]),
        incidents=tuple(d["incidents"]),
        timeline=tuple(_decode_timeline(t) for t in d["timeline"]),
    )


class RealizationReportStore:
    """Synchronous, sqlite3-backed, insert-only store for RealizationReports."""

    def __init__(self, db_path: str | Path, *, clock: Clock | None = None) -> None:
        self._clock = clock or (lambda: datetime.now(timezone.utc))
        self._conn = sqlite3.connect(str(db_path))
        self._conn.row_factory = sqlite3.Row
        with self._conn:
            self._conn.execute(_CREATE_TABLE_SQL)

    def close(self) -> None:
        self._conn.close()

    def record(self, report: RealizationReport) -> RealizationReport:
        """Inserts a new report — never updated, never deleted. A second
        generation for the same WorkItem always uses a new report_id."""
        try:
            with self._conn:
                self._conn.execute(
                    "INSERT INTO realization_reports (report_id, project_id, mvp_id, work_item_id, "
                    "generated_at, report_status, final_work_item_status, payload) "
                    "VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
                    (
                        report.report_id, report.project_id, report.mvp_id, report.work_item_id,
                        report.generated_at.isoformat(), report.report_status.value,
                        report.final_work_item_status, _serialize(report),
                    ),
                )
        except sqlite3.IntegrityError as exc:
            raise DuplicateRealizationReportError(report.report_id) from exc
        return report

    def get(self, report_id: str) -> RealizationReport:
        row = self._conn.execute(
            "SELECT * FROM realization_reports WHERE report_id = ?", (report_id,)
        ).fetchone()
        if row is None:
            raise UnknownRealizationReportError(report_id)
        try:
            return _deserialize(row["payload"])
        except (ValueError, TypeError, KeyError, json.JSONDecodeError) as exc:
            raise CorruptRealizationReportError(report_id, str(exc)) from exc

    def list_for_work_item(self, work_item_id: str) -> list[RealizationReport]:
        """Every report ever generated for a WorkItem, oldest first — none ever overwritten."""
        rows = self._conn.execute(
            "SELECT report_id FROM realization_reports WHERE work_item_id = ? ORDER BY generated_at ASC",
            (work_item_id,),
        ).fetchall()
        return [self.get(row["report_id"]) for row in rows]

    def latest_for_work_item(self, work_item_id: str) -> RealizationReport | None:
        reports = self.list_for_work_item(work_item_id)
        return reports[-1] if reports else None


# --- aggregation service -----------------------------------------------------


_INCIDENT_STATUSES = {ExecutionStatus.INTERRUPTED, ExecutionStatus.RECOVERY_REQUIRED}


def _derive_status(work_item_status: WorkItemStatus, *, has_handoffs: bool) -> RealizationReportStatus:
    if work_item_status is WorkItemStatus.COMPLETED:
        return RealizationReportStatus.COMPLETED
    if work_item_status is WorkItemStatus.FAILED:
        return RealizationReportStatus.FAILED
    if work_item_status is WorkItemStatus.BLOCKED:
        return RealizationReportStatus.BLOCKED
    if has_handoffs:
        return RealizationReportStatus.HANDOFF_READY
    return RealizationReportStatus.IN_PROGRESS


def _build_summary_text(
    *, work_item: WorkItem, report_status: RealizationReportStatus, executions: tuple[ExecutionEntry, ...],
    waits: tuple[WaitEntry, ...], incidents: tuple[str, ...],
) -> str:
    workers = sorted({e.worker_id for e in executions})
    sentences = [
        f"WorkItem {work_item.work_item_id!r} ({work_item.title}) was worked on by "
        f"{len(workers)} worker(s) across {len(executions)} execution(s)."
    ]
    if incidents:
        sentences.append(
            f"{len(incidents)} incident(s) were recorded during realization "
            "(see the Incidents section for details)."
        )
    if waits:
        sentences.append(f"{len(waits)} quota wait(s) occurred before completion.")
    if len(workers) > 1:
        sentences.append(f"Work was handed off across workers: {', '.join(workers)}.")
    sentences.append(f"Current report status: {report_status.value}.")
    return " ".join(sentences)


class RealizationReportService:
    """Builds a ``RealizationReport`` by aggregating already-persisted facts.

    Every store beyond the three required ones is optional, mirroring the
    opt-in composition already used throughout ``MVPManager`` — a project
    that never configured reviews/waits/adaptive execution simply gets an
    empty section for that part of the report, never an error.
    """

    def __init__(
        self,
        project_state_store: ProjectStateStore,
        execution_store: ExecutionStore,
        handoff_store: HandoffStore,
        report_store: RealizationReportStore,
        *,
        validation_store=None,
        review_store=None,
        wait_store=None,
        recommendation_store=None,
        decision_store=None,
        git_work_item_store=None,
        qa_run_store=None,
        clock: Clock | None = None,
        id_factory: IdFactory | None = None,
    ) -> None:
        self._project_state_store = project_state_store
        self._execution_store = execution_store
        self._handoff_store = handoff_store
        self._report_store = report_store
        self._validation_store = validation_store
        self._review_store = review_store
        self._wait_store = wait_store
        self._recommendation_store = recommendation_store
        self._decision_store = decision_store
        self._git_work_item_store = git_work_item_store
        self._qa_run_store = qa_run_store
        self._clock = clock or (lambda: datetime.now(timezone.utc))
        self._id_factory = id_factory or _default_id_factory

    def generate(self, *, project_id: str, mvp_id: str, work_item_id: str) -> RealizationReport:
        work_item = self._project_state_store.get_work_item(work_item_id)

        executions = tuple(
            _to_execution_entry(e) for e in self._execution_store.list_for_task(work_item_id)
        )
        handoffs = tuple(
            _to_handoff_entry(h) for h in self._handoff_store.list_for_work_item(work_item_id)
        )
        validations = (
            tuple(_to_validation_entry(v) for v in self._validation_store.list_results_for_work_item(work_item_id))
            if self._validation_store is not None else ()
        )
        reviews = (
            tuple(_to_review_entry(r) for r in self._review_store.list_for_work_item(work_item_id))
            if self._review_store is not None else ()
        )
        waits = (
            tuple(
                _to_wait_entry(w) for w in self._wait_store.list_for_mvp(mvp_id)
                if w.work_item_id == work_item_id
            )
            if self._wait_store is not None else ()
        )
        recommendations = (
            tuple(_to_recommendation_entry(r) for r in self._recommendation_store.list_for_work_item(work_item_id))
            if self._recommendation_store is not None else ()
        )
        decisions = (
            tuple(_to_decision_entry(d) for d in self._decision_store.list_for_work_item(work_item_id))
            if self._decision_store is not None else ()
        )

        git_work_item = (
            self._git_work_item_store.try_get(work_item_id)
            if self._git_work_item_store is not None else None
        )
        git_events = (
            tuple(self._git_work_item_store.list_events(work_item_id))
            if self._git_work_item_store is not None and git_work_item is not None else ()
        )

        qa_run = (
            self._qa_run_store.latest_for_work_item(work_item_id)
            if self._qa_run_store is not None else None
        )
        qa_result = (
            self._qa_run_store.get_result(qa_run.run_id)
            if self._qa_run_store is not None and qa_run is not None else None
        )
        qa_events = (
            tuple(self._qa_run_store.list_events(qa_run.run_id))
            if self._qa_run_store is not None and qa_run is not None else ()
        )

        incidents = _collect_incidents(
            work_item=work_item, executions=executions, validations=validations, reviews=reviews,
        )
        timeline = _build_timeline(
            executions=executions, recommendations=recommendations, decisions=decisions,
            handoffs=handoffs, validations=validations, reviews=reviews, waits=waits,
            git_events=git_events, qa_events=qa_events,
        )

        git_sha_initial = executions[0].git_sha_before if executions else None
        git_sha_after_values = [e.git_sha_after for e in executions if e.git_sha_after]
        git_sha_final = git_sha_after_values[-1] if git_sha_after_values else None

        report_status = _derive_status(work_item.status, has_handoffs=bool(handoffs))
        summary_text = _build_summary_text(
            work_item=work_item, report_status=report_status, executions=executions, waits=waits, incidents=incidents,
        )

        report = RealizationReport(
            report_id=self._id_factory(), project_id=project_id, mvp_id=mvp_id, work_item_id=work_item_id,
            generated_at=self._clock(), report_status=report_status, final_work_item_status=work_item.status.value,
            objective=work_item.title, summary_text=summary_text,
            acceptance_criteria=work_item.acceptance_criteria, dependencies=tuple(sorted(work_item.dependencies)),
            git_sha_initial=git_sha_initial, git_sha_final=git_sha_final,
            git_base_branch=git_work_item.base_branch if git_work_item is not None else None,
            git_work_branch=git_work_item.work_branch if git_work_item is not None else None,
            git_merge_status=git_work_item.status.value if git_work_item is not None else None,
            git_merged_sha=git_work_item.merged_sha if git_work_item is not None else None,
            git_pull_request_number=git_work_item.pull_request_number if git_work_item is not None else None,
            git_pull_request_url=git_work_item.pull_request_url if git_work_item is not None else None,
            qa_run_id=qa_run.run_id if qa_run is not None else None,
            qa_engine_id=qa_run.engine_id if qa_run is not None else None,
            qa_phase=qa_run.phase.value if qa_run is not None else None,
            qa_verdict_status=qa_run.verdict.status.value if qa_run is not None and qa_run.verdict is not None else None,
            qa_expected_head_sha=qa_run.expected_head_sha if qa_run is not None else None,
            qa_observed_head_sha=qa_result.observed_head_sha if qa_result is not None else None,
            qa_tests_executed_count=len(qa_result.tests_executed) if qa_result is not None else None,
            qa_passed_count=qa_result.passed_count if qa_result is not None else None,
            qa_failed_count=qa_result.failed_count if qa_result is not None else None,
            qa_regressions=qa_result.regressions if qa_result is not None else (),
            executions=executions, recommendations=recommendations, decisions=decisions, handoffs=handoffs,
            validations=validations, reviews=reviews, waits=waits, incidents=incidents, timeline=timeline,
        )
        return self._report_store.record(report)


def _to_execution_entry(e: ExecutionRecord) -> ExecutionEntry:
    return ExecutionEntry(
        execution_id=e.execution_id, role=e.role, worker_id=e.worker_id, provider=e.provider, backend=e.backend,
        model=e.model, reasoning_effort=e.reasoning_effort, started_at=e.started_at, finished_at=e.finished_at,
        status=e.status.value, exit_code=e.exit_code, provider_session_id=e.provider_session_id,
        ralph_loop_id=e.ralph_loop_id, git_sha_before=e.git_sha_before, git_sha_after=e.git_sha_after,
    )


def _to_handoff_entry(h: HandoffRecord) -> HandoffEntry:
    return HandoffEntry(
        handoff_id=h.handoff_id, created_at=h.created_at, execution_id=h.execution_id, worker_id=h.worker_id,
        completed_work=h.completed_work, decisions=h.decisions, files_touched=h.files_touched,
        tests_run=h.tests_run, test_results=h.test_results, open_issues=h.open_issues, risks=h.risks,
        next_action=h.next_action, git_sha_after=h.git_sha_after,
    )


def _to_validation_entry(v) -> ValidationEntry:
    return ValidationEntry(
        validation_run_id=v.validation_run_id, validation_id=v.validation_id, kind=v.kind.value,
        required=v.required, status=v.status.value, started_at=v.started_at, duration_ms=v.duration_ms,
        exit_code=v.exit_code, git_sha=v.git_sha,
    )


def _to_review_entry(r) -> ReviewEntry:
    return ReviewEntry(
        review_id=r.review_id, author_worker_id=r.author_worker_id, status=r.status.value,
        started_at=r.started_at, finished_at=r.finished_at, reviewer_worker_id=r.reviewer_worker_id,
        findings_summary=tuple(f"[{f.severity}] {f.summary}" for f in r.findings),
    )


def _to_wait_entry(w) -> WaitEntry:
    return WaitEntry(
        wait_id=w.wait_id, phase=w.phase.value, reason=w.reason.value, created_at=w.created_at,
        eligible_at=w.eligible_at, status=w.status.value, resolved_at=w.resolved_at, resolution=w.resolution,
    )


def _to_recommendation_entry(r) -> RecommendationEntry:
    return RecommendationEntry(
        recommendation_id=r.recommendation_id, role=r.role, estimator_worker_id=r.estimator_worker_id,
        estimator_execution_id=r.estimator_execution_id, estimator_profile_id=r.estimator_profile_id,
        task_fingerprint=r.task_fingerprint, minimum_quality_tier=r.minimum_quality_tier.name,
        recommended_reasoning=r.recommended_reasoning, reasons=r.reasons, created_at=r.created_at,
    )


def _to_decision_entry(d) -> DecisionEntry:
    return DecisionEntry(
        decision_id=d.decision_id, recommendation_id=d.recommendation_id, role=d.role, worker_id=d.worker_id,
        provider=d.provider, backend=d.backend, profile_id=d.profile_id, quality_tier=d.quality_tier.name,
        model=d.model, reasoning_effort=d.reasoning_effort, rationale=d.rationale, created_at=d.created_at,
    )


def _collect_incidents(
    *, work_item: WorkItem, executions: tuple[ExecutionEntry, ...], validations: tuple[ValidationEntry, ...],
    reviews: tuple[ReviewEntry, ...],
) -> tuple[str, ...]:
    incidents: list[str] = []
    for e in executions:
        if e.status in (ExecutionStatus.INTERRUPTED.value, ExecutionStatus.RECOVERY_REQUIRED.value):
            incidents.append(f"execution {e.execution_id} ended as {e.status}")
    for v in validations:
        if v.required and v.status not in ("passed", "skipped"):
            incidents.append(f"required validation {v.validation_id} ended as {v.status}")
    for r in reviews:
        if r.status == "rejected":
            incidents.append(f"review {r.review_id} rejected the work")
    if work_item.status is WorkItemStatus.BLOCKED and work_item.blocked_reason:
        incidents.append(f"work item blocked: {work_item.blocked_reason}")
    return tuple(incidents)


def _build_timeline(
    *, executions: tuple[ExecutionEntry, ...], recommendations: tuple[RecommendationEntry, ...],
    decisions: tuple[DecisionEntry, ...], handoffs: tuple[HandoffEntry, ...],
    validations: tuple[ValidationEntry, ...], reviews: tuple[ReviewEntry, ...], waits: tuple[WaitEntry, ...],
    git_events: tuple[tuple[str, str, datetime], ...] = (),
    qa_events: tuple[tuple[str, str, datetime], ...] = (),
) -> tuple[TimelineEntry, ...]:
    entries: list[TimelineEntry] = []

    for r in recommendations:
        entries.append(TimelineEntry(
            timestamp=r.created_at, entry_type=TIMELINE_RECOMMENDATION,
            summary=f"Pre-flight recommendation for role={r.role!r}: minimum_quality_tier={r.minimum_quality_tier}",
            references=(f"recommendation_id={r.recommendation_id}", f"estimator_worker_id={r.estimator_worker_id}"),
        ))
    for d in decisions:
        entries.append(TimelineEntry(
            timestamp=d.created_at, entry_type=TIMELINE_ADAPTIVE_DECISION,
            summary=f"Adaptive decision: worker={d.worker_id} profile={d.profile_id} tier={d.quality_tier}",
            references=(f"decision_id={d.decision_id}", f"recommendation_id={d.recommendation_id}"),
        ))
    for e in executions:
        entries.append(TimelineEntry(
            timestamp=e.started_at, entry_type=TIMELINE_EXECUTION_STARTED,
            summary=f"Execution started: role={e.role} worker={e.worker_id} model={e.model}",
            references=(f"execution_id={e.execution_id}",),
        ))
        if e.finished_at is not None:
            entries.append(TimelineEntry(
                timestamp=e.finished_at, entry_type=TIMELINE_EXECUTION_FINISHED,
                summary=f"Execution finished: status={e.status}",
                references=(f"execution_id={e.execution_id}",),
            ))
    for w in waits:
        entries.append(TimelineEntry(
            timestamp=w.created_at, entry_type=TIMELINE_WAIT_STARTED,
            summary=f"Wait started: phase={w.phase} reason={w.reason} eligible_at={w.eligible_at.isoformat()}",
            references=(f"wait_id={w.wait_id}",),
        ))
        if w.resolved_at is not None:
            entries.append(TimelineEntry(
                timestamp=w.resolved_at, entry_type=TIMELINE_WAIT_RESOLVED,
                summary=f"Wait resolved: {w.resolution}",
                references=(f"wait_id={w.wait_id}",),
            ))
    for h in handoffs:
        entries.append(TimelineEntry(
            timestamp=h.created_at, entry_type=TIMELINE_HANDOFF,
            summary=f"Handoff created: next_action={h.next_action or '(none)'}",
            references=(f"handoff_id={h.handoff_id}",),
        ))
    for v in validations:
        entries.append(TimelineEntry(
            timestamp=v.started_at, entry_type=TIMELINE_VALIDATION,
            summary=f"Quality gate {v.validation_id} ({v.kind}): {v.status}",
            references=(f"validation_run_id={v.validation_run_id}",),
        ))
    for r in reviews:
        entries.append(TimelineEntry(
            timestamp=r.started_at, entry_type=TIMELINE_REVIEW_STARTED,
            summary=f"Review started by author={r.author_worker_id}",
            references=(f"review_id={r.review_id}",),
        ))
        entries.append(TimelineEntry(
            timestamp=r.finished_at, entry_type=TIMELINE_REVIEW_FINISHED,
            summary=f"Review verdict: {r.status}",
            references=(f"review_id={r.review_id}",),
        ))
    for event_type, detail, created_at in git_events:
        entries.append(TimelineEntry(
            timestamp=created_at, entry_type=event_type,
            summary=f"Git governance: {event_type} — {detail}",
            references=(),
        ))
    for event_type, detail, created_at in qa_events:
        entries.append(TimelineEntry(
            timestamp=created_at, entry_type=f"qa_{event_type}",
            summary=f"QA: {event_type} — {detail}",
            references=(),
        ))

    # Deterministic ordering: chronological, ties broken by a stable,
    # fully-specified key so two reports built from identical facts always
    # render an identical timeline.
    entries.sort(key=lambda t: (t.timestamp, t.entry_type, t.summary, t.references))
    return tuple(entries)


# --- HTML rendering (pure, deterministic, no LLM, no external assets) -------


def _esc(value: object) -> str:
    return html_lib.escape(str(value)) if value is not None else "(none)"


def _status_color(status: RealizationReportStatus) -> str:
    return {
        RealizationReportStatus.COMPLETED: "#1a7f37",
        RealizationReportStatus.HANDOFF_READY: "#9a6700",
        RealizationReportStatus.IN_PROGRESS: "#0969da",
        RealizationReportStatus.BLOCKED: "#cf222e",
        RealizationReportStatus.FAILED: "#cf222e",
    }[status]


def _render_html(report: RealizationReport) -> str:
    parts: list[str] = []
    parts.append("<!doctype html>")
    parts.append('<html lang="en">')
    parts.append("<head>")
    parts.append('<meta charset="utf-8">')
    parts.append('<meta name="viewport" content="width=device-width, initial-scale=1">')
    parts.append(f"<title>Realization report — {_esc(report.work_item_id)}</title>")
    parts.append("""<style>
body { font-family: -apple-system, Segoe UI, Helvetica, Arial, sans-serif; margin: 0; padding: 16px;
       background: #f6f8fa; color: #1f2328; }
.container { max-width: 960px; margin: 0 auto; }
h1 { font-size: 1.4em; margin-bottom: 4px; }
h2 { font-size: 1.1em; margin-top: 28px; border-bottom: 1px solid #d0d7de; padding-bottom: 4px; }
.status-badge { display: inline-block; padding: 4px 10px; border-radius: 6px; color: #fff; font-weight: 600; }
.summary { background: #fff; border: 1px solid #d0d7de; border-radius: 6px; padding: 12px 16px; margin: 12px 0; }
table { border-collapse: collapse; width: 100%; margin: 8px 0 16px 0; background: #fff; }
th, td { border: 1px solid #d0d7de; padding: 6px 8px; text-align: left; font-size: 0.9em; word-break: break-word; }
th { background: #f6f8fa; }
.meta { color: #57606a; font-size: 0.85em; }
.timeline { list-style: none; padding-left: 0; }
.timeline li { border-left: 3px solid #d0d7de; padding: 4px 0 4px 12px; margin-bottom: 4px; }
.refs { color: #57606a; font-size: 0.8em; }
.empty { color: #57606a; font-style: italic; }
@media (max-width: 600px) { table, thead, tbody, th, td, tr { display: block; } th { display: none; }
  td { border: none; padding: 2px 0; } td::before { content: attr(data-label) ": "; font-weight: 600; } }
</style>""")
    parts.append("</head>")
    parts.append("<body><div class=\"container\">")

    parts.append(f"<h1>Realization report — {_esc(report.work_item_id)}</h1>")
    parts.append(
        f'<p><span class="status-badge" style="background:{_status_color(report.report_status)}">'
        f"{_esc(report.report_status.value.upper())}</span> "
        f"&nbsp; final WorkItem status: <strong>{_esc(report.final_work_item_status)}</strong></p>"
    )
    parts.append(
        f'<p class="meta">report_id={_esc(report.report_id)} · project_id={_esc(report.project_id)} · '
        f"mvp_id={_esc(report.mvp_id)} · generated_at={_esc(report.generated_at.isoformat())}</p>"
    )
    parts.append(f'<div class="summary">{_esc(report.summary_text)}</div>')

    parts.append("<h2>A. Objective</h2>")
    parts.append(f"<p>{_esc(report.objective)}</p>")
    parts.append("<p><strong>Acceptance criteria:</strong></p><ul>")
    for c in report.acceptance_criteria:
        parts.append(f"<li>{_esc(c)}</li>")
    parts.append("</ul>" if report.acceptance_criteria else '<p class="empty">(none)</p></ul>')
    if report.dependencies:
        parts.append(f"<p><strong>Dependencies:</strong> {_esc(', '.join(report.dependencies))}</p>")
    parts.append(
        f"<p><strong>Git SHA:</strong> initial={_esc(report.git_sha_initial)} -&gt; final={_esc(report.git_sha_final)}</p>"
    )
    if report.git_work_branch is not None:
        parts.append(
            "<p><strong>Git governance:</strong> "
            f"{_esc(report.git_base_branch)} &lt;- {_esc(report.git_work_branch)}, "
            f"status={_esc(report.git_merge_status)}"
            + (f", merged_sha={_esc(report.git_merged_sha)}" if report.git_merged_sha else "")
            + (
                f', PR <a href="{_esc(report.git_pull_request_url)}">'
                f"#{_esc(report.git_pull_request_number)}</a>"
                if report.git_pull_request_url else ""
            )
            + "</p>"
        )
    if report.qa_run_id is not None:
        parts.append(
            "<p><strong>QA:</strong> "
            f"engine={_esc(report.qa_engine_id)}, phase={_esc(report.qa_phase)}, "
            f"verdict={_esc(report.qa_verdict_status)}, "
            f"head={_esc(report.qa_expected_head_sha)}/observed={_esc(report.qa_observed_head_sha)}, "
            f"tests_executed={report.qa_tests_executed_count}, "
            f"passed={report.qa_passed_count}, failed={report.qa_failed_count}"
            + (f", regressions={_esc(', '.join(report.qa_regressions))}" if report.qa_regressions else "")
            + "</p>"
        )

    parts.append("<h2>B. Timeline</h2>")
    if report.timeline:
        parts.append('<ul class="timeline">')
        for t in report.timeline:
            refs = ", ".join(t.references)
            parts.append(
                f"<li><strong>{_esc(t.timestamp.isoformat())}</strong> — [{_esc(t.entry_type)}] {_esc(t.summary)}"
                + (f'<div class="refs">{_esc(refs)}</div>' if refs else "")
                + "</li>"
            )
        parts.append("</ul>")
    else:
        parts.append('<p class="empty">(no timeline entries)</p>')

    parts.append("<h2>C. Workers / Executions</h2>")
    if report.executions:
        parts.append(
            "<table><thead><tr><th>execution_id</th><th>role</th><th>worker</th><th>provider/backend</th>"
            "<th>model</th><th>reasoning</th><th>started</th><th>finished</th><th>status</th><th>exit</th>"
            "<th>git before -&gt; after</th></tr></thead><tbody>"
        )
        for e in report.executions:
            parts.append(
                "<tr>"
                f'<td data-label="execution_id">{_esc(e.execution_id)}</td>'
                f'<td data-label="role">{_esc(e.role)}</td>'
                f'<td data-label="worker">{_esc(e.worker_id)}</td>'
                f'<td data-label="provider/backend">{_esc(e.provider)}/{_esc(e.backend)}</td>'
                f'<td data-label="model">{_esc(e.model)}</td>'
                f'<td data-label="reasoning">{_esc(e.reasoning_effort)}</td>'
                f'<td data-label="started">{_esc(e.started_at.isoformat())}</td>'
                f'<td data-label="finished">{_esc(e.finished_at.isoformat() if e.finished_at else None)}</td>'
                f'<td data-label="status">{_esc(e.status)}</td>'
                f'<td data-label="exit">{_esc(e.exit_code)}</td>'
                f'<td data-label="git">{_esc(e.git_sha_before)} -&gt; {_esc(e.git_sha_after)}</td>'
                "</tr>"
            )
        parts.append("</tbody></table>")
    else:
        parts.append('<p class="empty">(no executions recorded)</p>')

    parts.append("<h2>D. Adaptive execution</h2>")
    if report.recommendations:
        parts.append(
            "<table><thead><tr><th>recommendation_id</th><th>role</th><th>estimator</th><th>tier</th>"
            "<th>reasoning hint</th><th>reasons</th></tr></thead><tbody>"
        )
        for r in report.recommendations:
            parts.append(
                "<tr>"
                f'<td data-label="recommendation_id">{_esc(r.recommendation_id)}</td>'
                f'<td data-label="role">{_esc(r.role)}</td>'
                f'<td data-label="estimator">{_esc(r.estimator_worker_id)} ({_esc(r.estimator_profile_id)})</td>'
                f'<td data-label="tier">{_esc(r.minimum_quality_tier)}</td>'
                f'<td data-label="reasoning hint">{_esc(r.recommended_reasoning)}</td>'
                f'<td data-label="reasons">{_esc("; ".join(r.reasons))}</td>'
                "</tr>"
            )
        parts.append("</tbody></table>")
    else:
        parts.append('<p class="empty">(no pre-flight recommendations recorded)</p>')
    if report.decisions:
        parts.append(
            "<table><thead><tr><th>decision_id</th><th>worker</th><th>profile</th><th>tier</th>"
            "<th>model</th><th>reasoning</th><th>rationale</th></tr></thead><tbody>"
        )
        for d in report.decisions:
            parts.append(
                "<tr>"
                f'<td data-label="decision_id">{_esc(d.decision_id)}</td>'
                f'<td data-label="worker">{_esc(d.worker_id)}</td>'
                f'<td data-label="profile">{_esc(d.profile_id)}</td>'
                f'<td data-label="tier">{_esc(d.quality_tier)}</td>'
                f'<td data-label="model">{_esc(d.model)}</td>'
                f'<td data-label="reasoning">{_esc(d.reasoning_effort)}</td>'
                f'<td data-label="rationale">{_esc(d.rationale)}</td>'
                "</tr>"
            )
        parts.append("</tbody></table>")
    else:
        parts.append('<p class="empty">(no adaptive decisions recorded)</p>')

    parts.append("<h2>E. Handoffs</h2>")
    if report.handoffs:
        for h in report.handoffs:
            parts.append(
                f"<div class=\"summary\"><strong>{_esc(h.handoff_id)}</strong> "
                f'<span class="meta">({_esc(h.created_at.isoformat())}, worker={_esc(h.worker_id)})</span><br>'
                f"completed_work: {_esc(h.completed_work)}<br>"
                f"decisions: {_esc(h.decisions)}<br>"
                f"test_results: {_esc(h.test_results)}<br>"
                f"open_issues: {_esc(h.open_issues)}<br>"
                f"next_action: {_esc(h.next_action)}<br>"
                f"files_touched: {_esc(', '.join(h.files_touched) or None)}<br>"
                f"git_sha_after: {_esc(h.git_sha_after)}</div>"
            )
    else:
        parts.append('<p class="empty">(no handoffs recorded)</p>')

    parts.append("<h2>F. Quality gates</h2>")
    if report.validations:
        parts.append(
            "<table><thead><tr><th>validation_id</th><th>kind</th><th>required</th><th>status</th>"
            "<th>exit</th><th>duration_ms</th><th>git SHA</th></tr></thead><tbody>"
        )
        for v in report.validations:
            parts.append(
                "<tr>"
                f'<td data-label="validation_id">{_esc(v.validation_id)}</td>'
                f'<td data-label="kind">{_esc(v.kind)}</td>'
                f'<td data-label="required">{_esc(v.required)}</td>'
                f'<td data-label="status">{_esc(v.status)}</td>'
                f'<td data-label="exit">{_esc(v.exit_code)}</td>'
                f'<td data-label="duration_ms">{_esc(v.duration_ms)}</td>'
                f'<td data-label="git SHA">{_esc(v.git_sha)}</td>'
                "</tr>"
            )
        parts.append("</tbody></table>")
    else:
        parts.append('<p class="empty">(no quality gate results recorded)</p>')

    parts.append("<h2>G. Reviews</h2>")
    if report.reviews:
        parts.append(
            "<table><thead><tr><th>review_id</th><th>author</th><th>reviewer</th><th>status</th>"
            "<th>findings</th></tr></thead><tbody>"
        )
        for r in report.reviews:
            parts.append(
                "<tr>"
                f'<td data-label="review_id">{_esc(r.review_id)}</td>'
                f'<td data-label="author">{_esc(r.author_worker_id)}</td>'
                f'<td data-label="reviewer">{_esc(r.reviewer_worker_id)}</td>'
                f'<td data-label="status">{_esc(r.status)}</td>'
                f'<td data-label="findings">{_esc("; ".join(r.findings_summary) or None)}</td>'
                "</tr>"
            )
        parts.append("</tbody></table>")
    else:
        parts.append('<p class="empty">(no reviews recorded)</p>')

    parts.append("<h2>H. Incidents</h2>")
    if report.incidents:
        parts.append("<ul>")
        for i in report.incidents:
            parts.append(f"<li>{_esc(i)}</li>")
        parts.append("</ul>")
    else:
        parts.append('<p class="empty">(none observed)</p>')

    if report.waits:
        parts.append("<h2>Quota waits</h2>")
        parts.append(
            "<table><thead><tr><th>wait_id</th><th>phase</th><th>reason</th><th>eligible_at</th>"
            "<th>status</th><th>resolution</th></tr></thead><tbody>"
        )
        for w in report.waits:
            parts.append(
                "<tr>"
                f'<td data-label="wait_id">{_esc(w.wait_id)}</td>'
                f'<td data-label="phase">{_esc(w.phase)}</td>'
                f'<td data-label="reason">{_esc(w.reason)}</td>'
                f'<td data-label="eligible_at">{_esc(w.eligible_at.isoformat())}</td>'
                f'<td data-label="status">{_esc(w.status)}</td>'
                f'<td data-label="resolution">{_esc(w.resolution)}</td>'
                "</tr>"
            )
        parts.append("</tbody></table>")

    parts.append("<h2>J. Final result</h2>")
    workers_used = sorted({e.worker_id for e in report.executions})
    parts.append("<ul>")
    parts.append(f"<li>Status: {_esc(report.report_status.value)}</li>")
    parts.append(f"<li>Executions: {_esc(len(report.executions))}</li>")
    parts.append(f"<li>Distinct workers: {_esc(', '.join(workers_used) or None)}</li>")
    parts.append(f"<li>Handoffs: {_esc(len(report.handoffs))}</li>")
    parts.append(f"<li>Quota waits: {_esc(len(report.waits))}</li>")
    parts.append("</ul>")

    parts.append("</div></body></html>")
    return "\n".join(parts)
